name: Approval Based Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    environment:
      name: development
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  
