name: Approval Based Deployment

on: 
   workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: D1
        options: 
        - D1
        - D2
        - P1
      updateConf:
        description: "Update Conf"
        required: true
        type: choice 
        default: 'no'
        options: 
        - 'yes'
        - 'no'
jobs:
  deploy:
   environment: 
      name: ${{ github.event.inputs.targetEnvironment }}
   runs-on: ubuntu-latest
   steps:
      - name: Enforce updateConf for P1
        run: |
          if [[ "${{ github.event.inputs.targetEnvironment }}" == "P1" && "${{ github.event.inputs.updateConf }}" == "yes" ]]; then
            echo "FLAG=false" >> $GITHUB_ENV
          else
            echo "FLAG=true" >> $GITHUB_ENV
          fi

      - name: Show flag value
        run: |
          echo "FLAG is $FLAG"

      - name: Proceed with deployment
        run: |
          echo "Proceeding with deployment to ${{ github.event.inputs.targetEnvironment }} with updateConf=${{ github.event.inputs.updateConf }}"
