name: Approval Based Deployment

on: 
   push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  
