name: Approval Based Deployment

on: 
   workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: D1
        options: 
        - D1
        - D2
        - P1
      updateConf:
        description: "Update Conf"
        required: true
        type: choice 
        default: 'no'
        options: 
        - 'yes'
        - 'no'
jobs:
  deploy:
   environment: 
      name: ${{ github.event.inputs.targetEnvironment }}
   runs-on: ubuntu-latest
   steps:
      - name: check on environment and update configuration value 
        run: |
           if [[ "${{ inputs.targetEnvironment }}" != "P1" && "${{ inputs.updateConf }}" == "yes" ]]; then
            echo "Cannot apply"
            exit 1
           else
             echo "can apply"
           fi
