name: Approval Based Deployment

on:
  pull_request_review:
    types: [submitted]
    

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  approval:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Workflow completed"
