name: Approval Based Deployment

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: d1
        options: 
        - d1
        - s1

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  approval:
    environment:
      name: d1
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Workflow completed"
