name: CCV2 Build

on:
  workflow_dispatch
    
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notification
        if: always()
        id: send_notification
        uses: rafal-slowik/gh-action-msteams@master
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      
