name: CCV2 Build

on:
  workflow_dispatch
    
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download SonarScanner CLI
        run: |
          curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -o sonar-scanner-cli.zip

      - name: Extract SonarScanner CLI
        run: |
          unzip sonar-scanner-cli.zip
          mv sonar-scanner-cli-5.0.1.3006 bin

      - name: Add SonarScanner CLI to PATH
        run: echo $PWD/bin >> $GITHUB_PATH
        
      - name: current path
        run: echo $pwd 
    
