name: CCV2 Build

on:
  pull_request_review:
    types: [submitted]
    
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  build:
    runs-on: ubuntu-latest
    steps:

    
    - name: Microsoft Teams Notification
      uses: jdcargile/ms-teams-notification@v1.4
      with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Github CCV2 Build for ${{ inputs.targetEnvironment }} environment.
          notification-color: 17a2b8
          timezone: America/Denver
          verbose-logging: true
