name: CCV2 Build

on:
  workflow_dispatch
    
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download SonarScanner CLI (Secure Way)
        # Download directly using curl with checksum verification
        run: |
          set -e  # Exit on failure

          # Download URL (replace with the desired version)
          DOWNLOAD_URL=https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip

          # Download the file
          curl -L "$DOWNLOAD_URL" -o sonar-scanner-cli.zip

          # Calculate checksum (adjust command based on checksum file provided by SonarSource)
          EXPECTED_CHECKSUM=$(curl -s https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip.sha256)
          ACTUAL_CHECKSUM=$(sha256sum sonar-scanner-cli.zip | cut -d ' ' -f 1)

          # Verify checksum (exit if mismatch)
          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
            echo "Error: Downloaded file checksum does not match expected value!"
            exit 1
          fi

      - name: Extract SonarScanner CLI
        run: unzip sonar-scanner-cli.zip
        # Consider error handling for failed unzip operation (optional)

      - name: Add SonarScanner CLI to PATH (Temporary)
        # Modify PATH only within this workflow
        run: echo $PWD/bin >> $GITHUB_PATH
        
      - name: current path
        run: echo $pwd 
    
