name: CCV2 Build

on:
  workflow_dispatch
    
env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Send pull requests to Microsoft Teams
        uses: metro-digital/ms-teams-notification-action@v1.0.3
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          
