name: CCV2 Deploy

on:
  workflow_dispatch:
    inputs:
      buildCode:
        description: "Build Code"
        type: string
        required: true
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: d1
        options: 
        - d1
        - s1
      systemUpdate:
        description: 'Platform Update Mode'
        required: true
        default: 'No migration required'
        type: choice
        options:
        - No migration required
        - Migrate data
      deploymentMode:
        description: 'Deployment Mode'
        required: true
        default: 'Rolling Update'
        type: choice
        options:
        - Rolling Update
        - Recreate

env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check if build is successfully done or not in CCV2 using API and then only deploy
      run: |
       echo ${{ inputs.targetEnvironment }}
       echo ${{ inputs.systemUpdate }}
       echo ${{ inputs.deploymentMode }}
       
  deployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: development
      url: 'http://mylocal.com'
    steps:
    - name: Deploy to Dev
      run: echo This id dev deploy  
    - name: Send email
      uses: cinotify/github-action@main
      with:
        to: 'kmanishkundanbhai@deloitte.com'
        subject: 'Test CCV2 Mail dev deploy section'
        body: '<em>This is a notification from GitHub actions for CCV2 Build.</em>'
        type: 'text/html'
