name: CCV2 Build and Deploy

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: d1
        options: 
        - d1
        - s1
      systemUpdate:
        description: 'Platform Update Mode'
        required: true
        default: 'No migration required'
        type: choice
        options:
        - No migration required
        - Migrate data
      deploymentMode:
        description: 'Deployment Mode'
        required: true
        default: 'Rolling Update'
        type: choice
        options:
        - Rolling Update
        - Recreate

env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print values
      run: |
       echo ${{ inputs.targetEnvironment }}
       echo ${{ inputs.systemUpdate }}
       echo ${{ inputs.deploymentMode }}

    - name: Request Approval (if s1 environment)
      uses: actions/github-script@v6
      with:
        script: |
            if (context.inputs.targetEnvironment === 's1') {
              core.setFailed('Approval required for s1 environment deployment!');
            }
    - name: Microsoft Teams Notifications
      uses: gor918/ms-teams-card-action@main
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: CCV2 Build 
        notification-color: 17a2b8
        timezone: Europe/Bucharest

    - name: Hello world
      run: |
        echo hello world
