name: CCV2 Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name_or_tag:
        description: "Branch name or tag"
        required: true
        type: string
        default: "main"
      environment:
        description: "Environment to deploy"
        required: true
        type: string
        default: d1
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: Print values
      run: |
       echo ${{ inputs.environment }}
       echo ${{ inputs.branch_name_or_tag }}
