name: CCV2 Build and Deploy

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: "Target Environment"
        required: true
        type: choice 
        default: d1
        options: 
        - d1
        - s1
      systemUpdate:
        description: 'Platform Update Mode'
        required: true
        default: 'No migration required'
        type: choice
        options:
        - No migration required
        - Migrate data
      deploymentMode:
        description: 'Deployment Mode'
        required: true
        default: 'Rolling Update'
        type: choice
        options:
        - Rolling Update
        - Recreate

env:
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  SUBSCRIPTION_CODE: ${{ secrets.SUBSCRIPTION_CODE }}
  

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print values
      run: |
       echo ${{ inputs.targetEnvironment }}
       echo ${{ inputs.systemUpdate }}
       echo ${{ inputs.deploymentMode }}
    - name: Send email
      uses: cinotify/github-action@main
      with:
        to: 'kmanishkundanbhai@deloitte.com'
        subject: 'Test CCV2 Mail'
        body: '<em>This is a notification from GitHub actions for CCV2 Build.</em>'
        type: 'text/html'
   
    - name: Microsoft Teams Notification
      uses: jdcargile/ms-teams-notification@v1.4
      with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Github CCV2 Build for ${{ inputs.targetEnvironment }} environment.
          notification-color: 17a2b8
          timezone: America/Denver
          verbose-logging: true
       
