name: test PR

on:
  workflow_dispatch

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print current date and time
        run: | 
          echo $(date +%F_%H-%M-%S)
          cat one.txt
      - name: Print hello world
        run: echo "Hello world" 
