name: CCV2 Build

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print current date and time
        run: echo $(date +%F_%H-%M-%S)
