name: Environment wise deployment
 
on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'Select an environment to deploy to?'
        required: true
        type: choice
        options:
          - development
          - D2
jobs:
  env_secrets:
    runs-on: ubuntu-latest    
    environment: ${{ github.event.inputs.environmentName }}
    steps:      
    - name: stage wise secrets
      run: |
        echo ${{ vars.URL }}
    - name: Notification
      if: always()
      id: send_notification
      uses: rafal-slowik/gh-action-msteams@master
      with:
        webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
